### PR TITLE
Feature more styling

### PR DESCRIPTION
**Pull request by AlvinWong13**

### CODE REVIEW

**Comment by patrickrnelson** [comment]
@AlvinWong13 On the climber page, I think the button needs to be Button

**Comment by patrickrnelson** [comment]
> @AlvinWong13 On the climber page, I think the button needs to be Button

137

**Comment by AlvinWong13** [comment]
updated @patrickrnelson

**Comment by patrickrnelson** [comment]
Very nice! Can't wait to see it!

**Pull request merged**
